### PR TITLE
Update to use graphql core 2.0

### PR DESCRIPTION
**Pull request by akand074**

### CODE REVIEW

**Comment by akand074** [comment]
@syrusakbary do you mind if we start a v2.0.dev version of this? I'm upgrading to graphene 2.0 and it requires graphql core > 2.0.dev

**Comment by akand074** [comment]
@syrusakbary pinging for some webob love :smile:

**Comment by syrusakbary** [comment]
Webob love accepted :)

**Comment by akand074** [comment]
Thanks! :heart:

**Pull request merged**
